################################################################################
#
# LIBRETRO DOLPHIN
#
################################################################################
# Version.: Commits on Oct 20, 2019
LIBRETRO_DOLPHIN_VERSION = 1fbd59911d1b718c142d6448dee3ede98152e395
LIBRETRO_DOLPHIN_SITE = $(call github,libretro,dolphin,$(LIBRETRO_DOLPHIN_VERSION))
LIBRETRO_DOLPHIN_LICENSE = GPLv2+
LIBRETRO_DOLPHIN_DEPENDENCIES = xserver_xorg-server libevdev ffmpeg zlib libpng lzo libusb libcurl sfml bluez5_utils qt5base hidapi
LIBRETRO_DOLPHIN_SUPPORTS_IN_SOURCE_BUILD = NO

LIBRETRO_DOLPHIN_CONF_OPTS  = -DLIBRETRO=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DCLANG=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
LIBRETRO_DOLPHIN_CONF_OPTS += -DTHREADS_PTHREAD_ARG=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_EGL=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DDISTRIBUTOR='Batocera.PLUS'

LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_VULKAN=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_X11=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_PULSEAUDIO=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF


define LIBRETRO_DOLPHIN_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/buildroot-build/dolphin_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/dolphin_libretro.so
endef

$(eval $(cmake-package))
