################################################################################
#
# LIBRETRO DOLPHIN
#
################################################################################

# Version.: Commits on Oct 23, 2020
# Libretro Dolphin
LIBRETRO_DOLPHIN_VERSION = 7510bb279a371a1c53ebe8dd20214df2eb89794e
LIBRETRO_DOLPHIN_SITE = $(call github,libretro,dolphin,$(LIBRETRO_DOLPHIN_VERSION))

# Libretro Ishiiruka
# Version.: Commits on Oct 3, 2020
#LIBRETRO_DOLPHIN_VERSION = f228bde5fbf4861ba749a229803addcd6238663f
#LIBRETRO_DOLPHIN_SITE = $(call github,libretro,Ishiiruka,$(LIBRETRO_DOLPHIN_VERSION))

LIBRETRO_DOLPHIN_LICENSE = GPLv2+
LIBRETRO_DOLPHIN_DEPENDENCIES = xserver_xorg-server libevdev ffmpeg zlib libpng lzo libusb libcurl bluez5_utils qt5base hidapi
LIBRETRO_DOLPHIN_SUPPORTS_IN_SOURCE_BUILD = NO

LIBRETRO_DOLPHIN_CONF_OPTS  = -DLIBRETRO=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DCLANG=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
LIBRETRO_DOLPHIN_CONF_OPTS += -DTHREADS_PTHREAD_ARG=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_EGL=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_ANALYTICS=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DDISTRIBUTOR='Batocera.PLUS'

LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_VULKAN=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_X11=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_PULSEAUDIO=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF


define LIBRETRO_DOLPHIN_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/buildroot-build/dolphin_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/dolphin_libretro.so
endef

$(eval $(cmake-package))
