#ifndef ALLEG_CTRL_H
#define ALLEG_CTRL_H

enum {
   KB_EMU_SCREENSHOT = 0,
   KB_EMU_INC_FRAMESKIP,
   KB_EMU_DEC_FRAMESKIP,
   KB_EMU_INC_CPU_FRAMESKIP,
   KB_EMU_DEC_CPU_FRAMESKIP,
   KB_EMU_SAVE_GAME,
   KB_EMU_SWITCH_SAVE_SLOT,
   KB_EMU_LOAD_GAME,
   KB_EMU_SWITCH_FPS,
   KB_EMU_RESET_GAME,
   KB_EMU_PAUSE_GAME,
   KB_EMU_STOP_EMULATION,
   KB_EMU_OPEN_GUI,
   KB_EMU_SCREEN_UP,
   KB_EMU_SCREEN_DOWN,
   KB_EMU_SCREEN_LEFT,
   KB_EMU_SCREEN_RIGHT,
   KB_EMU_SWITCH_MIXER,
   KB_EMU_SAVE_GAME_NAME,
   KB_EMU_LOAD_GAME_NAME,
   KB_EMU_SAVE_DEMO,
   KB_EMU_LOAD_DEMO,
   KB_EMU_REQ_FWD,
   KB_EMU_SAVE_VIDEO,
   KB_EMU_DEF_COUNT,
};

#endif
