#!/bin/sh
##
## Batocera.PLUS
## Encerra a execução do emulador rpcs3.
##
## Código escrito por: Sérgio de Carvalho Júnior
## 
################################################################################

PCSX2_PID="$(pidof -s PCSX2)"

kill -15 ${PCSX2_PID}
sleep 0.2

if [ -z "${PCSX2_PID}" ]; then
    echo 'PCSX2 closed!'
else
    sleep 0.5
    kill -9 ${PCSX2_PID}
    echo 'PCSX2 is dead!'
fi

exit 0