#!/bin/sh
##
## Batocera.PLUS
## Encerra a execução de todos os programas executados pelo wine.
##
## Código escrito por: Sérgio de Carvalho Júnior
## 
################################################################################

XEMU_PID="$(pidof -s xemu)"

kill -15 ${XEMU_PID}
sleep 0.2

if [ -z "${XEMU_PID}" ]; then
    echo 'Xemu closed!'
else
    sleep 0.5
    kill -9 ${XEMU_PID}
    echo 'Xemu is dead!'
fi

exit 0