#!/bin/sh

### Batocera.PLUS
### Encerra a execução de todos os programas executados pelo wine.
### Alexandre Freire dos Santos

if ! [ $(pidof -s wineserver) ]; then
    exit 1
fi

export WINEPREFIX="/$(ls -l "/proc/$(pidof -s wineserver)/fd" |
                      grep -E '/drive_c/windows/system32$' |
                      cut -d '/' -f 2- |
                      sed 's+/drive_c/windows/system32$++')"

wineserver -k

for i in {1..40}; do
    if ! [ $(pidof -s wineserver) ]; then
        exit 0
    else
        sleep 0.5
    fi

    if [ "${i}" == '40' ]; then
        killall -9 wineserver 2> /dev/null

        for i in $(ps ax | grep -E ".exe$|.EXE$" | awk '{print $1}'); do
            kill -9 "${i}" 2> /dev/null
        done

        exit 2
    fi
done
