#!/bin/sh

### Batocera.PLUS

if ! [ "${1}" == 'start' ]; then
  exit 0
fi

function spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}" > /dev/tty1
    done
}

for i in {1..300}; do
    if [ "${i}" == '1' ]; then
        clear  > /dev/tty1
        echo -n -e '\n Starting Batocera.PLUS' > /dev/tty1
        sleep 1
        echo -n '+' > /dev/tty1
        sleep 1
        spinner &
        sleep 1
    elif [ "$(pidof X)" ] || [ "${i}" == '300' ]; then
        kill "$!"
        clear > /dev/tty1
        echo -e '\n Batocera.PLUS' > /dev/tty1
        break
    else
        echo -n '+' > /dev/tty1
        sleep 0.50
    fi
done &

exit 0