#!/bin/sh
###
### Batocera.PLUS
### Alexandre Freire dos Santos
###
### Desinstala o driver proprietário da Nvidia quando
### o usuário salva as alterações usando o script
### batocera-save-overlay
###

if [ "${1}" != 'start' ]
then
    exit 0
fi

if [ -e '/boot/boot/overlay' ]
then
    /opt/Nvidia/uninstall.sh
fi

exit 0
