#!/bin/bash

### Batocera.PLUS
### Alexandre Freire dos Santos

SWAP_DEVS=$(grep "^[ ]*swap.partition[ ]*=[ ]*" /boot/batocera-boot.conf | cut -d '=' -f 2)

function findSwapDev()
{
    if [ -z "${SWAP_DEVS}" ]
    then
        return
    fi

    # Find swap partitions
    if [ "${SWAP_DEVS}" == 'auto' ]
    then
        SWAP_DEVS="$(LC_ALL=C fdisk -l | grep ' Linux swap$' | cut -d ' ' -f 1)"
    fi

    for SWAP_DEV in ${SWAP_DEVS}
    do
        # Check if swap device exist.
        if ! [ -e "${SWAP_DEV}" ]
        then
            return
        fi
    done
}

function zswapStart()
{
    findSwapDev

    # Enable zswap.
    echo 'Y'   > /sys/module/zswap/parameters/enabled
    echo 'lz4' > /sys/module/zswap/parameters/compressor

    # Enable swap.
    for SWAP_DEV in ${SWAP_DEVS}
    do
        if ! swapon -p 2 ${SWAP_DEV} 2> /dev/null
        then
            return
        fi
    done
}

function zswapStop()
{
    findSwapDev

    for SWAP_DEV in ${SWAP_DEVS}
    do
        swapoff ${SWAP_DEV}
    done
}

case "${1}" in
    start)
        zswapStart
        ;;
    stop)
        zswapStop
        ;;
    restart|reload)
        zswapStop
        sleep 1
        zswapStart
        ;;
    *)
        echo "usage: ${0}  start|stop|restart"
esac

exit 0
