#!/bin/bash

function showImage() {

    # Esta função e somente esta, é uma cópia exata da função "do_start" do arquivo orignal "S03splash" do batocera.linux.

    if [[ $(ls /boot/splash/*.{jpg,png}  2>/dev/null) ]]
    then
        image="$(ls /boot/splash/*.{jpg,png} | sed -e "$((RANDOM%$(ls -1 /boot/splash/*.{jpg,png} | wc -l)+1))!d")"
    else
        image="/usr/share/batocera/splash/logo-version.png"
    fi

    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
    sleep infinity
    wait $!
}

function spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}" > /dev/tty1
    done
}

function loadAnimationPlus() {
    for i in {1..240}; do
        if [ "${i}" == '1' ]; then
            clear  > /dev/tty1
            echo -n -e '\n Batocera.PLUS' > /dev/tty1
            sleep 1
            echo -n '+' > /dev/tty1
            sleep 1
            spinner &
            sleep 1
        elif [ -e /dev/fb0 ] || [ "$(pidof X)" ] || [ "${i}" == '240' ]; then
            kill "$!" 2> /dev/null
            clear > /dev/tty1
            break
        else
            echo -n '+' > /dev/tty1
            sleep 0.50
        fi
    done

    if ! grep -qE '^[ ]*splash.screen.enabled[ ]*=[ ]*0[ ]*$' "/boot/batocera-boot.conf"; then
        showImage &
    fi

    for i in {1..240}; do
        if [ "$(pidof X)" ] || [ -f /tmp/emulationstation.ready ] || [ "${i}" == '240' ]; then
            sleep 10
            echo -n -e '\n Batocera.PLUS' > /dev/tty1
            break
        fi
        sleep 1
    done
}

case "$1" in
    start)
        loadAnimationPlus &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
