#!/bin/bash

function showImage() {
    if [ -e /dev/fb0 ]; then
        if [ -f '/boot/splash.png' ]; then
	    image="/boot/splash.png"
        else
	    image='/usr/share/batocera/splash/logo-version.png'
        fi
        fbv -f -i "${image}"
    fi
}

function spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}" > /dev/tty1
    done
}

function loadAnimationPlus() {
    for i in {1..240}; do
        if [ "${i}" == '1' ]; then
            clear  > /dev/tty1
            echo -n -e '\n Starting Batocera.PLUS' > /dev/tty1
            sleep 1
            echo -n '+' > /dev/tty1
            sleep 1
            spinner &
            sleep 1
        elif [ -e /dev/fb0 ] || [ "$(pidof X)" ] || [ "${i}" == '240' ]; then
            kill "$!" 2> /dev/null
            clear > /dev/tty1
            break
        else
            echo -n '+' > /dev/tty1
            sleep 0.50
        fi
    done

    showImage

    for i in {1..240}; do
        if [ "$(pidof X)" ] || [ -f /tmp/emulationstation.ready ] || [ "${i}" == '240' ]; then
            sleep 3
            echo -n -e '\n Batocera.PLUS' > /dev/tty1
            break
        fi
        sleep 1
    done
}

case "$1" in
    start)
        loadAnimationPlus &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
