#!/bin/bash
###
### Batocera.PLUS
### Alexandre Freire dos Santos
###

if [ "${1}" != "start" ]
then
    exit 0
fi

CONFIG_FILE=/boot/batocera-boot.conf

NVIDIA_DRIVER=$(grep -E "^[ ]*nvidia-driver[ ]*=" ${CONFIG_FILE} | cut -d '=' -f 2 | xargs)

case ${NVIDIA_DRIVER} in
    auto)
        /opt/Nvidia/install.sh
        ;;
    last)
        /opt/Nvidia/install.sh last
        ;;
    390)
        /opt/Nvidia/install.sh v390
        ;;
    340)
        /opt/Nvidia/install.sh v340
        ;;
    false)
        /opt/Nvidia/uninstall.sh
        ;;
    *)
        /opt/Nvidia/install.sh
        ;;
esac

exit $?
