#!/bin/bash

### Batocera.PLUS

if [ "$1" != 'start' ]; then
  exit 0
fi

SHARE='/userdata'
DATAINIT='/usr/share/batocera/datainit'

### Cria pastas adicionais
mkdir -p "$SHARE/downloads"
mkdir -p "$SHARE/system/.local/share/Trash/files"
mkdir -p "$SHARE/system/configs/wine"

### Pasta splashvideos
if ! [ -d "$SHARE/splashvideos" ]; then
    cp -r "${DATAINIT}/splashvideos" "${SHARE}"
    ln -s '/opt/ControlPanel/splashvideos-config.plus' "${SHARE}/splashvideos/enable-disable-splashvideos.plus"
fi

### Arquivo de auto execução personalizado pelo usuário.
if ! [ -f "$SHARE/system/custom.sh" ]; then
    cp "$DATAINIT/system/custom.sh" "$SHARE/system/custom.sh"
fi

### Atalhos para a área de trabalho
if [ ! -e "${SHARE}/system/Desktop" ]; then
    mkdir -p "${SHARE}/system/Desktop"
    cp /usr/share/applications/firefox.desktop "${SHARE}/system/Desktop/Firefox.desktop"
fi

### Corrige problemas com fontes Chinesas.
if [ "$(grep system.language=zh_TW ${SHARE}/system/batocera.conf)" ] || [ "$(grep system.language=zh_CN ${SHARE}/system/batocera.conf)" ]; then
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/libretro/assets/xmb/monochrome/font.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/libretro/assets/ozone/regular.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjhbd.ttf' '/usr/share/libretro/assets/ozone/bold.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/fonts/truetype/nanum/NanumMyeongjo.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/fonts/dejavu/DejaVuSansMono.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjhbd.ttf' '/usr/share/fonts/dejavu/DejaVuSansMono-Bold.ttf'
fi

### Corrige problemas com o vulkan em placas de vídeo Intel.
if grep -qE "^[ ]*intel-i965-driver[ ]*=[ ]*true[ ]*$" /boot/batocera-boot.conf; then
    rm -f '/etc/X11/xorg.conf.d/20-intel.conf'
elif lsmod | grep -q '^i915 '; then
    echo -e \
        'Section "Device"\n' \
        '    Identifier  "Intel Graphics"\n' \
        '    Driver      "intel"\n' \
        '    Option      "DRI"    "3"\n' \
        'EndSection\n' > /etc/X11/xorg.conf.d/20-intel.conf
fi

exit 0
