#!/bin/bash

### Batocera.PLUS

if [ "$1" != 'start' ]; then
  exit 0
fi

SHARE='/userdata'
SHARE_INIT='/usr/share/batocera/datainit'

### Cria pastas adicionais
mkdir -p "$SHARE/downloads"
mkdir -p "$SHARE/system/.local/share/Trash/files"
mkdir -p "$SHARE/system/configs/wine"

### Pasta splashvideos
if ! [ -d "$SHARE/splashvideos" ]; then
    cp -r "${SHARE_INIT}/splashvideos" "${SHARE}"
fi

### Arquivo de auto execução personalizado pelo usuário.
if ! [ -f "$SHARE/system/custom.sh" ]; then
    cp "$SHARE_INIT/system/custom.sh" "$SHARE/system/custom.sh"
fi

### Copiar arquivos de configurações específicas para o retroarch.
if ! [ -d "${SHARE}/system/configs/retroarch" ]; then
    cp -r "${SHARE_INIT}/system/configs/retroarch" "${SHARE}/system/configs"
fi

### Corrige problemas com fontes Chinesas.
if [ "$(grep system.language=zh_TW ${SHARE}/system/batocera.conf)" ] || [ "$(grep system.language=zh_CN ${SHARE}/system/batocera.conf)" ]; then
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/libretro/assets/xmb/monochrome/font.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/libretro/assets/ozone/regular.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjhbd.ttf' '/usr/share/libretro/assets/ozone/bold.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/fonts/truetype/nanum/NanumMyeongjo.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjh.ttf'   '/usr/share/fonts/dejavu/DejaVuSansMono.ttf'
    ln -sf '/usr/share/fonts/truetype/msttcorefonts/msjhbd.ttf' '/usr/share/fonts/dejavu/DejaVuSansMono-Bold.ttf'
fi

exit 0
