#!/bin/bash
###
### Batocera.PLUS
### Sérgio de Carvalho Júnuior
###
################################################################################

start() {

    if [ -d '/mnt/storage' ]; then
        stop
    fi

    for HD in /media/* 
    do
        local FOLDER="${HD}"
        FOLDER="$(basename "${FOLDER}")"
        if [ -f "/media/${FOLDER}/system/batocera.conf" ] || [ -f "/media/${FOLDER}/boot/boot/batocera" ]; then
            continue
        else
            mkdir -p "/mnt/storage/${FOLDER}"
            mount --bind "/media/${FOLDER}" "/mnt/storage/${FOLDER}"
        fi
    done
}	

stop() {
	for HD in /mnt/storage/* 
    do
        local FOLDER="${HD}"
        FOLDER="$(basename "${FOLDER}")"
        umount "/mnt/storage/${FOLDER}" 2>&1&> /dev/null
        rmdir "/mnt/storage/${FOLDER}" 2>&1&> /dev/null
    done
    rmdir /mnt/storage
}	

restart() {
	stop
	start
	/etc/init.d/S91smb restart 2>&1&> /dev/null
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

