#!/bin/bash
###
### Batocera.PLUS
### Sérgio de Carvalho Júnuior
###
################################################################################

start() {

    stop

	for HD in /media/* 
    do
        FOLDER="${HD}"
        FOLDER="$(basename "${FOLDER}")"
		if [ -f "/media/${FOLDER}/system/batocera.conf" ] || [ -f "/media/${FOLDER}/boot/boot/batocera" ]; then
            continue
        else
            mkdir -p "/mnt/storage/${FOLDER}"
            mount --bind "/media/${FOLDER}" "/mnt/storage/${FOLDER}"
        fi
    done
}	

stop() {
	for HD in /mnt/storage/* 
    do
        FOLDER="${HD}"
        FOLDER="$(basename "${FOLDER}")"
        umount "/mnt/storage/${FOLDER}" 2>&1&> /dev/null
		if [ ! "$(ls -A "/mnt/storage/${FOLDER}" 2> /dev/null)" ]; then
		    rmdir "/mnt/storage/${FOLDER}" 2>&1&> /dev/null
        fi
    done
    rmdir /mnt/storage 2>&1&> /dev/null
}	

restart() {
	stop
	start
	/etc/init.d/S91smb restart 2>&1&> /dev/null
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

