# xSendKey
# Autor: Alexandre Freire dos Santos
# Email: alexxandre.freire@gmail.com
# Todos os direitos reservados 2018.

#xSendKey: xSendKey.c
#	cc -o xSendKey /usr/X11R6/lib/libX11.a xSendKey.c

xSendKey: xSendKey.c
	cc -o xSendKey -lX11 xSendKey.c

