#!/bin/sh

if [ "$#" -eq 0 ]; then
	programname=`basename "$0"`
	echo "ERROR: No program supplied"
	echo
	echo "Usage: $programname <program>"
	exit 1
fi

if [ "$1" = "--dlsym" ]; then
	MANGOHUD_DLSYM=1
	shift
fi

MANGOHUD_LIB_NAME="/opt/MangoHud/\$LIB/libMangoHud.so"

if [ "$MANGOHUD_DLSYM" = "1" ]; then
	MANGOHUD_LIB_NAME="/opt/MangoHud/\$LIB/libMangoHud_dlsym.so:${MANGOHUD_LIB_NAME}"
fi

if ! [ -e "${HOME}/.local/share/vulkan/implicit_layer.d/MangoHud.json" ]; then
    mkdir -p "${HOME}/.local/share/vulkan/implicit_layer.d/"
    ln -s /opt/MangoHud/MangoHud.json "${HOME}/.local/share/vulkan/implicit_layer.d/MangoHud.json"
fi

# Preload using the plain filesnames of the libs, the dynamic linker will
# figure out whether the 32 or 64 bit version should be used, and will search
# for it in the correct directory
LD_PRELOAD="${LD_PRELOAD}:${MANGOHUD_LIB_NAME}"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/MangoHud/\$LIB/"

exec env MANGOHUD=1 LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" LD_PRELOAD="${LD_PRELOAD}" "$@"
